# Generated by Django 5.2.1 on 2025-06-07 13:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reaction",
            unique_together={("user", "post")},
        ),
    ]
