# Generated by Django 5.2.1 on 2025-06-26 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_remove_post_image_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="image",
            new_name="image_data",
        ),
    ]
