# Generated by Django 5.2.1 on 2025-06-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_rename_image_image_image_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="reaction",
            field=models.IntegerField(
                choices=[(0, "None"), (-1, "Dislike"), (1, "Like")], default=0
            ),
        ),
    ]
