# Generated by Django 5.2.1 on 2025-06-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_alter_reaction_reaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reaction",
            old_name="reaction",
            new_name="type",
        ),
    ]
