# Generated by Django 5.2.1 on 2025-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_rename_reaction_reaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reaction",
            name="type",
            field=models.BooleanField(),
        ),
    ]
